version: 0.2
env:
  variables:
    S3_BUCKET: "cv.schreck.berlin"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd frontent
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
     commands:
      - aws s3 rm s3://wepay-darwin --recursive
      - aws s3 cp dist/ojoBancolombia s3://wepay-darwin --recursive --acl public-read-write
      - echo Build completed on `date`