version: 0.2
env:
  variables:
    S3_BUCKET: "cv.schreck.berlin"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - frontent
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
     commands:
      - aws s3 cp dist s3://compile-wepay --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes